name: Update gist
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
 workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                                                           
      - run: yarn install
      - name: Update gist
        uses: ./
        env:
          TIMEZONE: Asia/Shanghai
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NETEASE_GIST_ID: 0c3db70aa316f7be2ccefc63f4e5d591
          NETEASE_USER_ID: 105915001
          NETEASE_USER_TOKEN: ${{ secrets.USER_TOKEN }}
          MARKDOWN_FILE: README.md
      - name: Commit and push
        run: |-
          git config --global user.email "1129159201@qq.com" && git config --global user.name "rcy1314"
          git diff
          git add README.md && git commit -m ":robot: Github Action schedule automatically" || exit 0
          git pull --rebase && git push
