name: Update gist
on:

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - name: Update gist
        run: |
          const markdownFile = 'README.md';
          const fileReader = new FileReader();
          fileReader.onload = function(event) {
            const data = event.target.result;
            // 处理文件数据
            console.log(data);
          };
          fileReader.readAsText(markdownFile);
        env:
          TIMEZONE: Asia/Shanghai
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 0c3db70aa316f7be2ccefc63f4e5d591
          USER_ID: 105915001
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
