name: Update gist
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                                                           
      - run: yarn install
      - name: Update gist
        uses: ./
        env:
          TIMEZONE: Asia/Shanghai
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NETEASE_GIST_ID: 0c3db70aa316f7be2ccefc63f4e5d591
          NETEASE_USER_ID: 105915001
          NETEASE_USER_TOKEN: ${{ secrets.USER_TOKEN }}
          MARKDOWN_FILE: README.md
      
